# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Owen Williams
email: owen@char.gd
description: > # this means to ignore newlines until "baseurl:"
  Developer, writer, maker, human.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://festive-yonath-89aaee.netlify.com" # the base hostname & protocol for your site
twitter_username: ow
github_username:  ow
location: Amsterdam, Netherlands

services:
  - title: UX Writing
    description: Let your interface speak. Brilliant copy stands out in a world where voice is an afterthought in the design process, letting your product shine. 
    icon: far fa-pencil
    color: blue
  - title: Content
    description: Get your product in front of the right people. I'll help you build content that readers love, and converts them into customers.
    icon: far fa-rocket
    color: green
  - title: Technical Product Marketing
    description: Developers can smell marketing a mile away. Get your tools in the hands of the right people, with authentic marketing that doesn't stink.
    icon: far fa-bullhorn
    color: purple

career:
  - title: Digital Director
    company: VanMoof
    description: Built the engineering organization from the ground, moving app + web development in-house. Responsible for managing the engineering team, building out a digital strategy, and launching the brand into new countries online.
    icon: "/images/career/vanmoof.png"
    color: vanmoof
    dates: 
  - title: Editor
    company: The Next Web
    description: Telling stories about the people behind technology, writing news and breaking down complex topics for wide audiences. Managed implementation of performance-focused overhaul of the site, slashing loading times 60 percent.
    icon: "/images/career/tnw.png"
    color: tnw
  - title: Head of marketing / growth 
    company: Hoist
    description: Developing marketing strategy and executing it autonomously, reaching out to developers and coding our marketing site. Use wide range of analytics tools (Mixpanel, Crazyegg, Google Analytics) to iterate in real-time on strategy.
    icon: "/images/career/hoist.png"
    color: hoist
  - title: Infrastructure/Devops Engineer
    company: Xero
    description: Engineer on critical infrastructure team responsible for scaling the platform to millions of users. Supported product team to debug issues on the platform, optimized performance and built out a deployment pipeline for high availability.
    icon: "/images/career/xero.png"
    color: xero

collections:
- work

# Build settings
markdown: kramdown
permalink: pretty
exclude: [
  "node_modules",
  "LICENSE",
  "package.json",
  "README.md",
  "Gemfile",
  "gulpfile.babel.js",
  ".babelrc",
  ".gitignore",
  "sass",
  "scss",
  "validate"
]
